### ISSUE TITLE
RS School

### ISSUE THREAD

**Issue by bahnovak** [KrohNic/rsschool-cv#3]
Привет , https://bahnovak-english-for-kids.netlify.app/  статистика на месте , нажми на книжечку в меню .Спасибо !)

**Comment by KrohNic** [comment]
а кнопка  Repeat difficult words есть?
Пока поставил 165.

сб, 25 апр. 2020 г. в 23:11, bahnovak <notifications@github.com>:

**Comment by bahnovak** [comment]
Кнопки Repeat difficult нет, 165 заслуженная оценка)
